[package]
name = "nosracid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
chrono = "0.4"
uuid = { version = "0.8", features = ["v4"] }
